<script setup lang="ts">
const props = defineProps<{ value: string }>()

const colors: Record<string, string> = {
  线索: 'default',
  初洽: 'processing',
  尽调: 'cyan',
  谈判: 'gold',
  签约: 'purple',
  落地: 'green',
  搁置: 'default',
  起草中: 'default',
  待签署: 'gold',
  已生效: 'green',
  履行中: 'blue',
  已终止: 'red',
  新线索: 'blue',
  跟进中: 'gold',
  已转化: 'green',
  无效: 'default',
  待进行: 'blue',
  待纪要: 'gold',
  已完成: 'green',
  正常履约: 'green',
  即将到期: 'gold',
  逾期: 'red',
  来园接待: 'blue',
  外出拜访: 'purple',
  投资协议: 'geekblue',
  租赁合同: 'cyan',
  补充协议: 'gold',
  待处理: 'blue',
  进行中: 'processing',
  在园: 'green',
  重点: 'gold',
  待完善: 'orange',
  已迁出: 'default',
  可招商: 'blue',
  在租: 'green',
  已售: 'purple',
  装修中: 'gold',
  空置: 'red',
  申报中: 'blue',
  审核中: 'gold',
  待兑付: 'purple',
  已兑付: 'green',
  退回: 'red',
  筹备中: 'default',
  待接待: 'gold',
  已结束: 'default',
  草稿: 'default',
  已发布: 'green',
  启用: 'green',
  停用: 'default',
  园区: 'blue',
  部门: 'cyan',
  岗位: 'purple',
  推介会: 'geekblue',
  来园考察: 'blue',
  渠道沙龙: 'purple',
  外出招商: 'cyan',
  线索跟进: 'blue',
  拜访安排: 'cyan',
  合同审阅: 'gold',
  空间巡检: 'orange',
  政策审核: 'purple',
  研发楼: 'blue',
  厂房: 'cyan',
  中试楼: 'purple',
  配套: 'gold',
}
</script>

<template>
  <a-tag :color="colors[props.value] ?? 'default'">{{ props.value || '—' }}</a-tag>
</template>
